# Generated by Django 4.2.28 on 2026-03-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='dob',
        ),
    ]
