# Generated by Django 4.2.28 on 2026-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_remove_voter_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
