# Generated by Django 4.2.28 on 2026-03-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
